version: "3.9"
services:
  node0: 
    image: test:latest
    container_name: node0-test
    expose:
      - "9090"
      - "7946"
    environment:
      - NODEID=0
    networks:
      - net-lamport
  node1: 
    image: test:latest
    container_name: node1-test
    expose:
      - "9090"
      - "7946"
    environment:
      - NODEID=1
    depends_on:
      - node0
    networks:
      - net-lamport
  node2: 
    image: test:latest
    container_name: node2-test
    expose:
      - "9090"
      - "7946"
    environment:
      - NODEID=2      
    depends_on:
      - node0
    networks:
      - net-lamport   
  node3: 
    image: test:latest
    container_name: node3-test
    expose:
      - "9090"
      - "7946"
    environment:
      - NODEID=3      
    depends_on:
      - node0
    networks:
      - net-lamport 
networks:
  net-lamport:
    ipam:
      config:
        - subnet: 172.20.4.0/24
